package common;

public enum MessageType {

    ARRIVAL_LOUNGE_TAKE_A_REST,
    ARRIVAL_LOUNGE_NO_MORE_BAGS_TO_COLLECT,
    ARRIVAL_LOUNGE_TRY_TO_COLLECT_A_BAG,
    ARRIVAL_LOUNGE_WHAT_SHOULD_I_DO,
    ARRIVAL_LOUNGE_INIT_PLANE_HOLD,


    ARRIVAL_TERMINAL_TRANSFER_QUAY_TAKE_A_BUS,
    ARRIVAL_TERMINAL_TRANSFER_QUAY_WAIT_FOR_BUS,
    ARRIVAL_TERMINAL_TRANSFER_QUAY_ENTER_THE_BUS,

    DEPARTURE_TERMINAL_TRANSFER_QUAY_LEAVE_THE_BUS,


    DEPARTURE_TERMINAL_ENTRACE_PREPARE_NEXT_LEG,


    ARRIVAL_TERMINAL_EXIT_GO_HOME,


    REPOSITORY_INIT,
    REPOSITORY_REMOVE_LUGGAGE_IN_PLANE_HOLD,
    REPOSITORY_REMOVE_PASSENGER_FROM_BUS,
    REPOSITORY_REGISTER_PASSENGER_TO_ENTER_THE_BUS,
    REPOSITORY_REGISTER_PASSENGER_TO_TAKE_A_BUS,
    REPOSITORY_REGISTER_COLLECTED_LUGGAGE,
    REPOSITORY_REGISTER_LUGGAGE_IN_STORE_ROOM,
    REPOSITORY_REGISTER_LUGGAGE_IN_CONVEYOR_BELT,
    REPOSITORY_FLIGHT_LANDED,
    REPOSITORY_SET_PORTER_STATE,
    REPOSITORY_SET_BUS_DRIVER_STATE,
    REPOSITORY_SET_PASSENGER_STATE



}
